### ISSUE TITLE
Set operations/methods

### ISSUE THREAD

**Issue by peterjwest** [tc39/proposal-javascript-standard-library#36]
I don't know if these are already planned, but it would be great to have standard Set operations e.g. union, intersect, except.

**Comment by zloirock** [comment]
https://github.com/tc39/proposal-set-methods, https://github.com/tc39/proposal-collection-methods, https://github.com/tc39/proposal-setmap-offrom

**Comment by littledan** [comment]
Closing this issue to pursue in those proposal repositories instead.
