### ISSUE TITLE
Rename repo to proposal-builtin-modules

### ISSUE THREAD

**Issue by MylesBorins** [tc39/proposal-javascript-standard-library#57]
I was under the impression that at a previous meeting there was a decision to rename this proposal. Am I mistaken?

**Comment by chicoxyzzy** [comment]
Yes, it was June 2019 meeting in Berlin https://github.com/tc39/tc39-notes/blob/master/meetings/2019-06/june-5.md#conclusionresolution-8

**Comment by chicoxyzzy** [comment]
Duplicate of https://github.com/tc39/proposal-javascript-standard-library/issues/53 🙂
